# Generated by Django 5.2.8 on 2025-11-16 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='회차 번호', unique=True)),
                ('draw_date', models.DateTimeField(blank=True, help_text='추첨일', null=True)),
                ('winning_numbers', models.CharField(blank=True, help_text='당첨 번호 (쉼표로 구분)', max_length=100)),
                ('bonus_number', models.PositiveSmallIntegerField(blank=True, help_text='보너스 번호', null=True)),
                ('is_drawn', models.BooleanField(default=False, help_text='추첨 완료 여부')),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(help_text='선택한 번호 (쉼표로 구분, 정렬됨)', max_length=100)),
                ('is_auto', models.BooleanField(default=False, help_text='자동 생성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lotto_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lotto.lottoround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WinningResult',
            fields=[
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lotto.lottoticket')),
                ('rank', models.PositiveSmallIntegerField(help_text='당첨 등수 (1~5, 0은 꽝)')),
            ],
        ),
    ]
